# .github/workflows/snaplogic-cicd.yml

name: SnapLogic CI/CD

on:
  push:
    branches:
      - Dev-Branch
  # workflow_dispatch: # (Optional manual trigger)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Merge Dev to Prod branch
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: Dev-Branch
          target_branch: Prod-Branch
          github_token: ${{ secrets.ACTIONS_TOKEN }}

      - name: Deploy assets to SnapLogic Prod project
        run: |
          curl -s -X POST \
            "https://elastic.snaplogic.com/api/1/rest/public/project/pull/SEDemo/Dylan%20Vetter/prod_space" \
            -H "Content-Type: application/json" \
            -H "Authorization: Basic ${{ secrets.DV_SNAPLOGIC_BASE64 }}" \
            -d '{"use_theirs":"true"}'
